version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  webserver:
    build:
      context: ./docker/apache
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - mysql
    ports:
    - "8081:80"
    volumes:
      - /sessions
    links:
      - mysql


volumes:
  dbdata:
